### ISSUE TITLE
oAuth2-Patinfo

### ISSUE THREAD

**Issue by i4mi** [i4mi/midata.js#2]
Unlike the MIDATA API the FHIR API does not provide specific user information after successful authentication. This information is needed though in order to query records later on. Therefore, the library needs to be extended so that this information is obtained and securely stored during the applications' 'logged in' scope.

TODO
- Upon retrieval of access_token ( GET -> /fhir/Patient)
- Extract and store user info (_id & name) into user object and invoke _setLoginData()

**Comment by wyssa14** [comment]
Currently only the owner's _id gets stored in the patient object. The name property (mail address) is set to "mockuser@midata.coop" since it's not implicitly available (e.g. returned with the http response etc.). Also, in the near future it most likely won't be used anymore and applications could easily query this information after the login process (GET -> /fhir/Patient). Anyway, i did not delete the property as for now in order to assure backward compatibility...
